// Response exato do sandbox do Bradesco para consulta de extrato.
// Usado pelo endpoint GET /mock/bradesco/extrato e como fallback do
// extrato-client quando BRADESCO_EXTRATO_URL não está configurada.
export const mockExtratoBradesco = {
  extratoUltimosLancamentos: {
    codigoRetorno: '00',
    mensagem: 'CTAS0673 - CONSULTA EFETUADA COM SUCESSO',
    identificaoCliente: '0',
    razaoConta: '00705',
    numeroConta: '75557',
    digitoConta: '5',
    nomeCliente: 'CONTA AMBIENTE TU',
    quantidadeLancamentos: '8',
    statusContaCorrente: '0',
    statusContaPoupanca: '0',
    identificadorTipoConta: 'conta corrente',
    statusCoberturaAutomatica: '0',
    contaPoupancaFacil: '0000000',
    dataUltimaAtualizacao: '      ',
    identificadorModalidadeConta: ' ',
    dataProximoPagamentoInss: '00000000',
    dataVencimentoCartaoInss: '000000',
    statusCartaoInss: '',
    listaLancamentos: {
      'Saldo Anterior': [
        {
          sinalSaldo: '+',
          valorLancamento: '0,00',
          segundaLinhalLancamento: '',
          sinalLancamento: '',
          identificacaoSubCodigo: 'S',
          numeroDocumento: '0000000',
          valorSaldoAposLancamento: '6.759,00',
          dataLancamento: '10/12/2024',
        },
      ],
      'Ultimos Lancamentos': [
        {
          sinalSaldo: '+',
          valorLancamento: '1,15',
          segundaLinhalLancamento: '',
          sinalLancamento: '+',
          identificacaoSubCodigo: 'N',
          codigoLancamento: '03584',
          descritivoLancamentoAbreviado: 'RENT.INV.FACIL',
          numeroDocumento: '0000003',
          valorSaldoAposLancamento: '6.760,15',
          dataLancamento: '17/01/2025',
          descritivoLancamentoCompleto: 'RENTAB.INVEST FACILCRED*',
        },
        {
          sinalSaldo: '+',
          valorLancamento: '800,00',
          segundaLinhalLancamento: '',
          sinalLancamento: '+',
          identificacaoSubCodigo: 'N',
          codigoLancamento: '00101',
          descritivoLancamentoAbreviado: 'RESGATE AUT INV',
          numeroDocumento: '0000004',
          valorSaldoAposLancamento: '7.560,15',
          dataLancamento: '17/01/2025',
          descritivoLancamentoCompleto: 'RESG AUTOMATICO INVESTIM',
        },
        {
          sinalSaldo: '+',
          valorLancamento: '100,00',
          segundaLinhalLancamento: 'TESTE VANESSA 1',
          sinalLancamento: '+',
          identificacaoSubCodigo: 'N',
          codigoLancamento: '00997',
          descritivoLancamentoAbreviado: 'COD. LANC. 00997',
          numeroDocumento: '0000005',
          valorSaldoAposLancamento: '7.660,15',
          dataLancamento: '17/01/2025',
          descritivoLancamentoCompleto: 'COD. LANC. 00997',
        },
        {
          sinalSaldo: '+',
          valorLancamento: '210,01',
          segundaLinhalLancamento: 'TESTE VANESSA 2',
          sinalLancamento: '+',
          identificacaoSubCodigo: 'N',
          codigoLancamento: '00998',
          descritivoLancamentoAbreviado: 'CHQ COMPENSADO',
          numeroDocumento: '0000006',
          valorSaldoAposLancamento: '7.870,16',
          dataLancamento: '21/01/2025',
          descritivoLancamentoCompleto: 'CHEQUE COMPENSADO',
        },
        {
          sinalSaldo: '+',
          valorLancamento: '210,00',
          segundaLinhalLancamento: 'TESTE VANESSA 3',
          sinalLancamento: '+',
          identificacaoSubCodigo: 'N',
          codigoLancamento: '00771',
          descritivoLancamentoAbreviado: 'AC CTA N RECADA',
          numeroDocumento: '0000007',
          valorSaldoAposLancamento: '8.080,16',
          dataLancamento: '21/01/2025',
          descritivoLancamentoCompleto: 'ACERTO CONTA N/RECADAST*',
        },
      ],
      'Lancamentos Dia': [
        {
          sinalSaldo: '+',
          valorLancamento: '15,00',
          segundaLinhalLancamento: 'REM: EMPRESA PAGADOR       22/01',
          sinalLancamento: '+',
          identificacaoSubCodigo: 'N',
          codigoLancamento: '03212',
          descritivoLancamentoAbreviado: 'TRANSFE PIX',
          numeroDocumento: '0936269',
          valorSaldoAposLancamento: '8.095,16',
          dataLancamento: '22/01/2025',
          descritivoLancamentoCompleto: 'TRANSFERENCIA PIX',
        },
        {
          sinalSaldo: '+',
          valorLancamento: '72,95',
          segundaLinhalLancamento: 'REM: TESTE CHAVES          22/01',
          sinalLancamento: '+',
          identificacaoSubCodigo: 'N',
          codigoLancamento: '03212',
          descritivoLancamentoAbreviado: 'TRANSFE PIX',
          numeroDocumento: '0948412',
          valorSaldoAposLancamento: '8.168,11',
          dataLancamento: '22/01/2025',
          descritivoLancamentoCompleto: 'TRANSFERENCIA PIX',
        },
      ],
    },
  },
  extratoLancamentosFuturos: {
    codigoRetorno: '00',
    mensagem: 'CTAS0673 - CONSULTA EFETUADA COM SUCESSO',
    quantidadeLancamentos: '5',
    listaLancamentos: {
      'Lancamentos Futuros': [
        {
          valorLancamento: '1.233,00',
          segundaLinhalLancamento: '',
          sinalLancamento: '+',
          identificacaoSubCodigo: 'N',
          codigoLancamento: '00112',
          descritivoLancamentoAbreviado: 'TRANSF.AUT. C/C',
          numeroDocumento: '0015446',
          dataLancamento: '03/02/2025',
          descritivoLancamentoCompleto: 'TRANSF.AUTORIZ.ENTRE C/C',
        },
        {
          valorLancamento: '478,02',
          segundaLinhalLancamento: '',
          sinalLancamento: '+',
          identificacaoSubCodigo: 'N',
          codigoLancamento: '00112',
          descritivoLancamentoAbreviado: 'TRANSF.AUT. C/C',
          numeroDocumento: '0004545',
          dataLancamento: '03/02/2025',
          descritivoLancamentoCompleto: 'TRANSF.AUTORIZ.ENTRE C/C',
        },
        {
          valorLancamento: '600,01',
          segundaLinhalLancamento: '',
          sinalLancamento: '+',
          identificacaoSubCodigo: 'N',
          codigoLancamento: '00110',
          descritivoLancamentoAbreviado: 'APL AUT FUNDOS',
          numeroDocumento: '1223113',
          dataLancamento: '10/02/2025',
          descritivoLancamentoCompleto: 'APLICACAO AUTOMAT FUNDOS',
        },
        {
          valorLancamento: '701,55',
          segundaLinhalLancamento: '',
          sinalLancamento: '+',
          identificacaoSubCodigo: 'N',
          codigoLancamento: '00554',
          descritivoLancamentoAbreviado: 'COMP COMPL PARC',
          numeroDocumento: '0122332',
          dataLancamento: '10/02/2025',
          descritivoLancamentoCompleto: 'COMPENS COMPLEMENTO PARC',
        },
        {
          valorLancamento: '910,00',
          segundaLinhalLancamento: '',
          sinalLancamento: '+',
          identificacaoSubCodigo: 'N',
          codigoLancamento: '00970',
          descritivoLancamentoAbreviado: 'EST2V CART DEB',
          numeroDocumento: '0444404',
          dataLancamento: '15/02/2025',
          descritivoLancamentoCompleto: 'EST 2VIA CARTAO DEBITO',
        },
      ],
    },
  },
  extratoPorPeriodo: {
    codigoRetorno: '00',
    mensagem: 'CTAS0673 - CONSULTA EFETUADA COM SUCESSO',
    identificaoCliente: '1',
    razaoConta: '00705',
    numeroConta: '75557',
    digitoConta: '5',
    nomeCliente: 'CONTA AMBIENTE TU               ',
    quantidadeLancamentos: '12',
    lstLancamentoMensal: [
      {
        dataLancamento: '30/09/2024',
        numeroDocumento: '0000000',
        valorLancamento: '0,00',
        sinalLancamento: '+',
        segundaLinhalLancamento: '',
        valorSaldoAposLancamento: '80,00',
        sinalSaldo: '+',
        identificacaoSubCodigo: null,
        tipoLancamento: '01',
        codigoLancamento: '00000',
        descritivoLancamentoAbreviado: 'Saldo Anterior',
        descritivoLancamentoCompleto: 'Saldo Anterior',
        dataDebitoCpmf: '0000000',
        valorCpmf: '000000000000000',
      },
      {
        dataLancamento: '01/10/2024',
        numeroDocumento: '0000001',
        valorLancamento: '700,00',
        sinalLancamento: '-',
        segundaLinhalLancamento: '',
        valorSaldoAposLancamento: '620,00',
        sinalSaldo: '-',
        identificacaoSubCodigo: null,
        tipoLancamento: '02',
        codigoLancamento: '03205',
        descritivoLancamentoAbreviado: 'TRANSFE PIX',
        descritivoLancamentoCompleto: 'TRANSFERENCIA PIX',
        dataDebitoCpmf: '0000000',
        valorCpmf: '000000000000000',
      },
      {
        dataLancamento: '05/10/2024',
        numeroDocumento: '0000001',
        valorLancamento: '800,00',
        sinalLancamento: '+',
        segundaLinhalLancamento: '',
        valorSaldoAposLancamento: '180,00',
        sinalSaldo: '+',
        identificacaoSubCodigo: null,
        tipoLancamento: '02',
        codigoLancamento: '03205',
        descritivoLancamentoAbreviado: 'TRANSFE PIX',
        descritivoLancamentoCompleto: 'TRANSFERENCIA PIX',
        dataDebitoCpmf: '0000000',
        valorCpmf: '000000000000000',
      },
      {
        dataLancamento: '15/10/2024',
        numeroDocumento: '0000001',
        valorLancamento: '600,00',
        sinalLancamento: '+',
        segundaLinhalLancamento: '',
        valorSaldoAposLancamento: '780,00',
        sinalSaldo: '+',
        identificacaoSubCodigo: null,
        tipoLancamento: '02',
        codigoLancamento: '03205',
        descritivoLancamentoAbreviado: 'TRANSFE PIX',
        descritivoLancamentoCompleto: 'TRANSFERENCIA PIX',
        dataDebitoCpmf: '0000000',
        valorCpmf: '000000000000000',
      },
      {
        dataLancamento: '20/10/2024',
        numeroDocumento: '0000001',
        valorLancamento: '500,00',
        sinalLancamento: '+',
        segundaLinhalLancamento: '',
        valorSaldoAposLancamento: '1.280,00',
        sinalSaldo: '+',
        identificacaoSubCodigo: null,
        tipoLancamento: '02',
        codigoLancamento: '03205',
        descritivoLancamentoAbreviado: 'TRANSFE PIX',
        descritivoLancamentoCompleto: 'TRANSFERENCIA PIX',
        dataDebitoCpmf: '0000000',
        valorCpmf: '000000000000000',
      },
      {
        dataLancamento: '28/10/2024',
        numeroDocumento: '0000001',
        valorLancamento: '400,00',
        sinalLancamento: '-',
        segundaLinhalLancamento: '',
        valorSaldoAposLancamento: '880,00',
        sinalSaldo: '+',
        identificacaoSubCodigo: null,
        tipoLancamento: '02',
        codigoLancamento: '03205',
        descritivoLancamentoAbreviado: 'TRANSFE PIX',
        descritivoLancamentoCompleto: 'TRANSFERENCIA PIX',
        dataDebitoCpmf: '0000000',
        valorCpmf: '000000000000000',
      },
      {
        dataLancamento: '01/11/2024',
        numeroDocumento: '0000001',
        valorLancamento: '550,00',
        sinalLancamento: '-',
        segundaLinhalLancamento: '',
        valorSaldoAposLancamento: '330,00',
        sinalSaldo: '+',
        identificacaoSubCodigo: null,
        tipoLancamento: '02',
        codigoLancamento: '03205',
        descritivoLancamentoAbreviado: 'TRANSFE PIX',
        descritivoLancamentoCompleto: 'TRANSFERENCIA PIX',
        dataDebitoCpmf: '0000000',
        valorCpmf: '000000000000000',
      },
      {
        dataLancamento: '05/11/2024',
        numeroDocumento: '0000002',
        valorLancamento: '860,00',
        sinalLancamento: '+',
        segundaLinhalLancamento: '',
        valorSaldoAposLancamento: '1.190,00',
        sinalSaldo: '+',
        identificacaoSubCodigo: null,
        tipoLancamento: '02',
        codigoLancamento: '03205',
        descritivoLancamentoAbreviado: 'TRANSFE PIX',
        descritivoLancamentoCompleto: 'TRANSFERENCIA PIX',
        dataDebitoCpmf: '0000000',
        valorCpmf: '000000000000000',
      },
      {
        dataLancamento: '15/11/2024',
        numeroDocumento: '0000003',
        valorLancamento: '688,00',
        sinalLancamento: '+',
        segundaLinhalLancamento: '',
        valorSaldoAposLancamento: '1.878,00',
        sinalSaldo: '+',
        identificacaoSubCodigo: null,
        tipoLancamento: '02',
        codigoLancamento: '03205',
        descritivoLancamentoAbreviado: 'TRANSFE PIX',
        descritivoLancamentoCompleto: 'TRANSFERENCIA PIX',
        dataDebitoCpmf: '0000000',
        valorCpmf: '000000000000000',
      },
      {
        dataLancamento: '03/12/2024',
        numeroDocumento: '0000001',
        valorLancamento: '101,50',
        sinalLancamento: '+',
        segundaLinhalLancamento: '',
        valorSaldoAposLancamento: '1.979,50',
        sinalSaldo: '+',
        identificacaoSubCodigo: null,
        tipoLancamento: '02',
        codigoLancamento: '03210',
        descritivoLancamentoAbreviado: 'RECB QRCODE PIX',
        descritivoLancamentoCompleto: 'RECB. QRCODE DINAMIC PIX',
        dataDebitoCpmf: '0000000',
        valorCpmf: '000000000000000',
      },
      {
        dataLancamento: '11/12/2024',
        numeroDocumento: '0000002',
        valorLancamento: '210,15',
        sinalLancamento: '+',
        segundaLinhalLancamento: '',
        valorSaldoAposLancamento: '2.189,65',
        sinalSaldo: '+',
        identificacaoSubCodigo: null,
        tipoLancamento: '02',
        codigoLancamento: '03212',
        descritivoLancamentoAbreviado: 'TRANSFE PIX',
        descritivoLancamentoCompleto: 'TRANSFERENCIA PIX',
        dataDebitoCpmf: '0000000',
        valorCpmf: '000000000000000',
      },
      {
        dataLancamento: '13/12/2024',
        numeroDocumento: '0000003',
        valorLancamento: '1,15',
        sinalLancamento: '+',
        segundaLinhalLancamento: '',
        valorSaldoAposLancamento: '2.190,80',
        sinalSaldo: '+',
        identificacaoSubCodigo: null,
        tipoLancamento: '02',
        codigoLancamento: '03584',
        descritivoLancamentoAbreviado: 'RENT.INV.FACIL',
        descritivoLancamentoCompleto: 'RENTAB.INVEST FACILCRED*',
        dataDebitoCpmf: '0000000',
        valorCpmf: '000000000000000',
      },
    ],
  },
};

export type ExtratoBradesco = typeof mockExtratoBradesco;

export interface LancamentoMensal {
  dataLancamento: string;
  numeroDocumento: string;
  valorLancamento: string;
  sinalLancamento: string;
  segundaLinhalLancamento: string;
  valorSaldoAposLancamento: string;
  sinalSaldo: string;
  identificacaoSubCodigo: string | null;
  tipoLancamento: string;
  codigoLancamento: string;
  descritivoLancamentoAbreviado: string;
  descritivoLancamentoCompleto: string;
  dataDebitoCpmf: string;
  valorCpmf: string;
}
